### ISSUE TITLE
preprocess.py: default batch size of 120 gets error on 1080ti

### ISSUE THREAD

**Issue by hiveai** [tangbinh/image-captioning#3]
In preprocess.py when using the default batch size of 120, on a 1080ti with 11GB RAM, I get a "RuntimeError: CUDA error: out of memory".  
I tried a batch size of 80 and it seems to work.  I'd suggest reducing the default batch size

**Comment by tangbinh** [comment]
Thank you for your suggestion. I've been using 16GB GPUs, so a batch size of 120 seems to maximize utility. However, I've change the default value to 80 just in case 12GB GPUs are more common. See  commit [97b1053](https://github.com/tangbinh/image-captioning/commit/be8ee9c02395df4d84f9864c4dbb98b6697b1053).
